### ISSUE TITLE
[QST] How to configure to run multiple Concurrent Tasks on single GPU for Spark RAPIDS Jobs?

### ISSUE THREAD

**Issue by vara-bonthu** [NVIDIA/spark-rapids#11586]
**What is your question?**
I  am currently running [PySpark data processing jobs](https://github.com/KubedAI/spark-rapids-on-kubernetes/blob/main/examples/benchmarks/benchmark/spark-rapids-benchmarks.py) to read partitioned CSV data from S3 and perform some aggregations. The same script is being run on both CPU and GPU instances using Spark RAPIDS. However, I am noticing that _`Spark RAPIDS on GPU is significantly slower than CPU`_, especially when loading partitioned CSV data from S3 using the s3a protocol.

**Issue:**
When running on CPUs, I can see that all **4 cores** are being fully utilized, running 4+ tasks in parallel per executor. However, when using GPUs with Spark RAPIDS, each GPU node is only running **1 task per nod**e, resulting in underutilization and much slower performance (up to 4 times slower than CPU).

[GPU Spark Rapids config](https://github.com/KubedAI/spark-rapids-on-kubernetes/blob/bb2dc53bf33399e0ba0038c5b69604fa3e489354/examples/benchmarks/benchmark/benchmark-gpu.yaml#L44C4-L74C41)

```yaml
  "spark.rapids.sql.concurrentGpuTasks": "4" # 2 tasks on g6.4x large takes 32 mins and 4 tasks takes: 
    "spark.executor.resource.gpu.amount": "1"
    "spark.rapids.memory.pinnedPool.size": "2g"
    "spark.executor.memoryOverhead": "3g"
    "spark.sql.files.maxPartitionBytes": "512m"
    "spark.sql.shuffle.partitions": "10"
    "spark.plugins": "com.nvidia.spark.SQLPlugin"
    "spark.shuffle.manager": "com.nvidia.spark.rapids.spark351.RapidsShuffleManager"
    "spark.executor.resource.gpu.discoveryScript": "/opt/sparkRapidsPlugin/getGpusResources.sh"
    "spark.executor.resource.gpu.vendor": "nvidia.com"
    "spark.executor.extraLibraryPath": "/usr/local/cuda/lib:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/targets/x86_64-linux/lib:/usr/lib/hadoop/lib/native:/usr/lib/hadooplzo/lib/native:/docker/usr/lib/hadoop/lib/native:/docker/usr/lib/hadoop-lzo/lib/native"
    "spark.task.cpus": "4"
    "spark.dynamicAllocation.enabled": "false"
    "spark.rapids.sql.enabled": "true"
    "spark.rapids.cloudSchemes": "s3a"
    "spark.rapids.memory.gpu.pool": "ASYNC"
    "spark.rapids.memory.gpu.allocFraction": "0.8"  # Adjusted to avoid exceeding GPU memory limits
    "spark.rapids.memory.gpu.maxAllocFraction": "0.9"  # Ensure it's consistent
    "spark.rapids.memory.gpu.minAllocFraction": "0.25"
    "spark.rapids.sql.shuffle.spillThreads": "16"
    "spark.rapids.sql.batchSizeBytes": "512m"
    "spark.rapids.sql.reader.batchSizeBytes": "512m"
    "spark.rapids.sql.metrics.level": "MODERATE"  # Optional, set to DEBUG if needed
    "spark.rapids.sql.explain": "ALL"  # Optional for debugging
    "spark.rapids.sql.stableSort.enabled": "true"
    "spark.rapids.sql.variableFloatAgg.enabled": "false"
    "spark.task.resource.gpu.amount": "0.25" # experimenting
    "spark.rapids.sql.explain": "NOT_ON_GPU"
    "spark.rapids.sql.incompatibleOps.enabled": "true"
    "spark.rapids.shuffle.mode": "MULTITHREADED"
    "spark.sql.adaptive.enabled": "true"
-
-
-
executor:
    cores: 4
    instances: 4  # Single executor with one GPU - aiming for g5 or g6 xlarge
    memory: "10g"
    gpu:
      name: "nvidia.com/gpu"
      quantity: 1
```

[CPU PySpark Config](https://github.com/KubedAI/spark-rapids-on-kubernetes/blob/bb2dc53bf33399e0ba0038c5b69604fa3e489354/examples/benchmarks/benchmark/benchmark-cpu.yaml#L27)

```yaml

  executor:
    cores: 4
    instances: 2  
    memory: "10g"
    labels:
      version: "3.5.1"
```

**Despite trying multiple configurations, the GPU seems to be running only 1 task per node, while CPUs are efficiently running 4+ tasks per node.**

**Screenshots:**
In the attached screenshots, you can see the difference between the Spark History Server for both CPU and GPU runs:
![Image](https://github.com/user-attachments/assets/f70b5e7f-c2a7-4f7d-bb24-10fd2a341020)

Left (CPU): Shows 5 active tasks per node.
Right (GPU): Shows only 1 active task per node.

**Questions:**
How can I ensure that multiple tasks can run concurrently on a single GPU, similar to how multiple tasks run on multiple CPU cores?

Is there any specific configuration I am missing that could enable better utilization of the GPU for Spark workloads?

Are there any known limitations or best practices for running Spark tasks on GPUs that might explain this behavior?

Is it recommended to use one instance with multiple GPUs instead of using 4 instances with 1 GPU each?
