### ISSUE TITLE
[FEA] New Github workflow to add new issues to spark-rapids project

### ISSUE THREAD

**Issue by mattahrens** [NVIDIA/spark-rapids#6639]
**Is your feature request related to a problem? Please describe.**
I would like to have a workflow added to add any new spark-rapids issue to the spark-rapids project: https://github.com/orgs/NVIDIA/projects/4.  The workflow can follow examples listed here: https://github.com/actions/add-to-project. 

Exact syntax would be something like this:

```
name: Add new issues to spark-rapids project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to spark-rapids project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/NVIDIA/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
```
