### ISSUE TITLE
[BUG] OOM of NDS2 queries on Dataproc 2.1-preview(Spark-3.3.0)

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#7032]
**Describe the bug**
I see several NDS queries run into OOM error w/ Iceberg enabled. While the query w/o Iceberg but w/ pure Parquet can run successfully.
Dataset scale factor: 3000

The failed queries are:
- [] 4
- [] 14a,b
- [] 19
- [] 24a,b
- [] 37
- [] 72
- [] 82
- [] 84

**Steps/Code to reproduce bug**
1. build jar locally with the following diff:
```
   diff --git a/pom.xml b/pom.xml
index 6d155840c..05fc3daa3 100644
--- a/pom.xml
+++ b/pom.xml

@@ -1116,7 +1116,7 @@
-        <iceberg.version>0.13.2</iceberg.version>
+        <iceberg.version>0.14.1</iceberg.version>
```
3. create a Dataproc cluster with 2.1-preview image
```
gcloud dataproc clusters import CLUSTER_NAME --region=us-central1 --source=dataproc-cluster.yaml
```
with the following yaml file
```
---
projectId: rapids-spark
clusterName: cluster-b275
config:
  configBucket: ''
  gceClusterConfig:
    networkUri: ''
    subnetworkUri: default
    internalIpOnly: false
    zoneUri: us-central1-b
    metadata: {}
    tags: []
    shieldedInstanceConfig:
      enableSecureBoot: false
      enableVtpm: false
      enableIntegrityMonitoring: false
  masterConfig:
    numInstances: 1
    machineTypeUri: n1-standard-32
    diskConfig:
      bootDiskType: pd-standard
      bootDiskSizeGb: 500
      numLocalSsds: 0
      localSsdInterface: NVME
    minCpuPlatform: ''
    imageUri: ''
  softwareConfig:
    imageVersion: preview-ubuntu
    properties: {}
    optionalComponents: []
  lifecycleConfig: {}
  initializationActions:
  - executableFile: gs://nds2-dataset/spark-rapids.sh
  encryptionConfig:
    gcePdKmsKeyName: ''
  autoscalingConfig:
    policyUri: ''
  endpointConfig:
    enableHttpPortAccess: true
  securityConfig:
    kerberosConfig: {}
  workerConfig:
    numInstances: '4'
    machineTypeUri: n1-standard-32
    diskConfig:
      bootDiskType: pd-standard
      bootDiskSizeGb: 500
      numLocalSsds: 8
      localSsdInterface: NVME
    accelerators:
    - acceleratorTypeUri: nvidia-tesla-t4
      acceleratorCount: 2
    minCpuPlatform: 'Intel Skylake'
    imageUri: ''
  secondaryWorkerConfig:
    numInstances: 0
labels: {}
status: {}
statusHistory:
- {}
metrics: {}
```
Note, please remove all built-in jars first:
```
for i in {0..3}
do
    gcloud compute ssh --zone "us-central1-b" "CLUSTER_NAME-w-$i"  --project "rapids-spark" --command 'sudo rm /usr/lib/spark/jars/rapids-4-spark_2.12-22.08.0.jar'
done

gcloud compute ssh --zone "us-central1-b" "CLUSTER_NAME-m"  --project "rapids-spark" --command 'sudo rm /usr/lib/spark/jars/rapids-4-spark_2.12-22.08.0.jar'
```

5. get spark-rapids-benchmarks repo on the cluster
6. set dataset path and generate query stream files(please ping me offline and I can share the gs bucket path with you including stream files)

**Environment details (please complete the following information)**
cluster config: see yaml file above
spark app config: 
```
export SPARK_HOME=${SPARK_HOME:-/usr/lib/spark}
export SPARK_MASTER=${SPARK_MASTER:-yarn}
export DRIVER_MEMORY=${DRIVER_MEMORY:-30G}
export EXECUTOR_CORES=${EXECUTOR_CORES:-16}
export NUM_EXECUTORS=${NUM_EXECUTORS:-8}
export EXECUTOR_MEMORY=${EXECUTOR_MEMORY:-32G}
 
export CONCURRENT_GPU_TASKS=${CONCURRENT_GPU_TASKS:-1}
export SHUFFLE_PARTITIONS=${SHUFFLE_PARTITIONS:-800}
 
export SPARK_CONF=("--master" "${SPARK_MASTER}"
--deploy-mode "client"
--conf "spark.driver.maxResultSize=2GB"
--conf "spark.driver.memory=${DRIVER_MEMORY}"
--conf "spark.executor.cores=${EXECUTOR_CORES}"
--conf "spark.executor.instances=${NUM_EXECUTORS}"
--conf "spark.executor.memory=${EXECUTOR_MEMORY}"
--conf "spark.executor.memoryOverhead=16G"
--conf "spark.sql.shuffle.partitions=${SHUFFLE_PARTITIONS}"
--conf "spark.sql.autoBroadcastJoinThreshold=10m"
--conf "spark.sql.files.maxPartitionBytes=512mb"
--conf "spark.sql.adaptive.enabled=true"
--conf "spark.executor.resource.gpu.amount=1"
--conf "spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh"
--conf "spark.task.resource.gpu.amount=0.0625"
--conf "spark.plugins=com.nvidia.spark.SQLPlugin"
--conf "spark.rapids.memory.host.spillStorageSize=32G"
--conf "spark.rapids.memory.pinnedPool.size=8g"
--conf "spark.rapids.sql.concurrentGpuTasks=${CONCURRENT_GPU_TASKS}"
--packages "org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:0.14.1"
--conf "spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
--conf "spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog"
--conf "spark.sql.catalog.spark_catalog.type=hadoop"
--files "$SPARK_HOME/examples/src/main/scripts/getGpusResources.sh"
```

submit the job by
```
/usr/lib/spark/bin/spark-submit \
--master yarn --deploy-mode client \
--conf spark.driver.maxResultSize=2GB \
--conf spark.driver.memory=30G \
--conf spark.executor.cores=16 \
--conf spark.executor.instances=8 \
--conf spark.ecutor.memory=50G \
--conf spark.executor.memoryOverhead=16G \
--conf spark.sql.shuffle.partitions=800 \
--conf spark.sql.autoBroadcastJoinThreshold=10m \
--conf spark.sql.files.maxPartitionBytes=512mb \
--conf spark.sql.adaptive.enabled=true \
--conf spark.executor.resource.gpu.amount=1 \
--conf srk.executor.resource.gpu.discoveryScript=./getGpusResources.sh \
--conf spark.task.resource.gpu.amount=0.0625 \
--conf spark.plugins=com.nvidia.spark.SQLPlugin \
--conf spark.rapids.memory.host.spillStorageSize=32G \
--conf spark.rapids.memory.pinnedPool.size=8g \
--conf spark.rapids.sql.concuentGpuTasks=1 \
--packages org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:0.14.1 \
--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
--conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog \
--conf spark.sql.catalogpark_catalog.type=hadoop \
--files /usr/lib/spark/examples/src/main/scripts/getGpusResources.sh \
--jars /home/allxu_nvidia_com/rapids-4-spark_2.12-22.12.0-SNAPSHOT-cuda11.jar \
nds_power.py \
gs://nds2-dataset/iceberg-warehouse-3k bench_streams/query19.sql \
power_test_1101_gpu.csv \
--input_foat iceberg \
--property_file properties/aqe-on.properties
```
