### ISSUE TITLE
[BUG] GPU Parquet output for TIMESTAMP_MICROS is misinteterpreted by fastparquet as nanos

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#8778]
**Describe the bug**
GPU Parquet timestamp is misinterpreted as nanos by fastparquet. Output produced by Identical code on the CPU is interpreted by fastparquet correctly.

**Steps/Code to reproduce bug**
```Python
df = spark.createDataFrame([(datetime.datetime(3023, 7, 14, 7, 38, 45, 418688),)], 'ts timestamp')
cpu_path = tempfile.mkdtemp("cpu_ts")
gpu_path = tempfile.mkdtemp("gpu_ts")
spark.conf.set('spark.sql.parquet.outputTimestampType', 'TIMESTAMP_MICROS')
```

#### On CPU, Spark and fastparquet are consistent

```Python
spark.conf.set('spark.rapids.sql.enabled', False)
df.write.mode('overwrite').parquet(cpu_path)
cpu_file, = glob.glob(f"{cpu_path}/*.parquet")
spark.read.parquet(cpu_path).show(truncate = False)
fastparquet.ParquetFile(cpu_file).head(1)
```
Out
```
+--------------------------+
|ts                        |
+--------------------------+
|3023-07-14 07:38:45.418688|
+--------------------------+

                          ts
0 3023-07-14 07:38:45.418688
```

#### GPU's output appears corrupt when read by fastparquet 
```Python
spark.conf.set('spark.rapids.sql.enabled', True)
df.write.mode('overwrite').parquet(gpu_path)
gpu_file, = glob.glob(f"{gpu_path}/*.parquet")
spark.read.parquet(gpu_path).show(truncate = False)
fastparquet.ParquetFile(gpu_file).head(1)
```

Out
```
+--------------------------+
|ts                        |
+--------------------------+
|3023-07-14 07:38:45.418688|
+--------------------------+

                             ts
0 1854-06-04 08:29:37.999584768
```

The issue appears to be in the GPU case, fast parquet assumes logical time unit nanos 
```
OrderedDict([('max_ts', dtype('<M8[ns]')), ('max_big_ts', dtype('<M8[ns]'))])
```
because unlike in the CPU case GPU output does not have the logicalType metadata 

```Python
fastparquet.ParquetFile(cpu_file).fmd
```

```
...
 logicalType:
    BSON: null
    DATE: null
    DECIMAL: null
    ENUM: null
    INTEGER: null
    JSON: null
    LIST: null
    MAP: null
    STRING: null
    TIME: null
    TIMESTAMP:
      isAdjustedToUTC: true
      unit:
        MICROS: {}
        MILLIS: null
        NANOS: null
    UNKNOWN: null
    UUID: null
```

**Expected behavior**
spark-rapids should be interoperable with non-Spark parquet readers, at least with the ones that work with upstream Spark 

**Environment details (please complete the following information)**
 - Environment location: any
 - Spark configuration settings related to the issue: `spark.sql.parquet.outputTimestampType='TIMESTAMP_MICROS'`

**Additional context**
encountered working on #8625
